### PR TITLE
Upgrade to .Net 8, Update Packages

### PR DESCRIPTION
**Pull request by Woife1978**

### CODE REVIEW

**Comment by lechu445** [comment]
@Woife1978 What benefits brings this change? Does it solve some issue?

**Comment by Woife1978** [comment]
No function changes madeAm 04.02.2024 13:55 schrieb "Leszek B." ***@***.***>:
@Woife1978 What benefits brings this change? Does it solve some issue?

**Comment by lechu445** [comment]
This change drops support for old .NET, in particular it drops support for .NET Framework. Sorry, but I am not going to merge it without presented any benefits.

**Comment by Woife1978** [comment]
OkAm 04.02.2024 18:48 schrieb "Leszek B." ***@***.***>:
This change drops support for old .NET, in particular it drops support for .NET Framework. Sorry, but I am not going to merge it without presented any benefits.

**Comment by lechu445** [comment]
I will close it for now. There is no clear benefit of this change and, for now, there is no pain to keep support for old versions of .NET. In case the compatibility will become an issue, then I will come back to it.

**Pull request closed without merging**
